import {
  FiBell,
  FiBookOpen,
  FiBriefcase,
  FiCalendar,
  FiCircle,
  FiDollarSign,
  FiFileText,
  FiGrid,
  FiHome,
  FiLock,
  FiLogOut,
  FiMapPin,
  FiRefreshCw,
  FiSettings,
  FiShield,
  FiTrendingUp,
  FiUser,
  FiUsers,
} from 'react-icons/fi';
import { ROLES } from '../../utils/roles';

const PAGE_ICON_COMPONENTS = {
  dashboard: FiHome,
  attendance: FiCalendar,
  announcements: FiBell,
  analytics: FiTrendingUp,
  'employee-profile': FiUser,
  team: FiUsers,
  employees: FiUsers,
  'leave-management': FiCalendar,
  leaves: FiCalendar,
  payroll: FiDollarSign,
  performance: FiTrendingUp,
  reports: FiBookOpen,
  settings: FiSettings,
  'team-collaboration': FiUsers,
  'dashboard-overview': FiHome,
  'leaves-attendance': FiCalendar,
  'manpower-planning': FiBriefcase,
  'hr-payroll': FiDollarSign,
  'exit-clearance': FiLogOut,
  'meeting-room': FiMapPin,
  workflows: FiRefreshCw,
  'letter-templates': FiFileText,
  'user-management': FiUser,
  masters: FiGrid,
  'admin-panel-config': FiSettings,
  departments: FiBriefcase,
  'roles-permissions': FiLock,
  'system-settings': FiSettings,
  'audit-logs': FiFileText,
  'ui-components': FiGrid,
};

export const attachMonoIconsToPages = (pages = []) => {
  return pages.map((page) => ({
    ...page,
    icon: typeof page.icon === 'function' ? page.icon : PAGE_ICON_COMPONENTS[page.id] || FiCircle,
  }));
};

export const ROLE_DASHBOARD_CONFIG = {
  [ROLES.EMPLOYEE]: {
    portalLabel: 'Employee Self-Service',
    heading: 'My Work Dashboard',
    subtitle: 'Manage attendance, leave, payroll, and documents in one place.',
    widgets: [
      { key: 'attendance', title: 'Attendance This Month', value: '0', note: 'Live attendance summary from your daily records' },
      { key: 'leaves', title: 'My Leave Requests', value: '0', note: 'Submitted and approved leave requests from backend' },
      { key: 'holidays', title: 'Upcoming Holidays', value: '0', note: 'Holiday calendar synced from company leave policy' },
      { key: 'payslip', title: 'Payslips Available', value: '0', note: 'Payroll statements available for secure download' },
    ],
    pages: [
      { id: 'dashboard', label: 'Dashboard', icon: FiHome, category: 'main', description: 'Personal HR summary and quick actions' },
      { id: 'attendance', label: 'Attendance', icon: FiCalendar, category: 'work', description: 'Daily punch history and attendance status' },
      { id: 'announcements', label: 'Announcements', icon: FiBell, category: 'work', description: 'Company updates and important notices' },
      { id: 'employee-profile', label: 'Employee Profile', icon: FiUser, category: 'work', description: 'Personal information and employment details' },
      { id: 'leaves', label: 'Leaves', icon: FiCalendar, category: 'work', description: 'Apply leave and track request progress' },
      { id: 'payroll', label: 'Payroll', icon: FiDollarSign, category: 'work', description: 'Payslips, deductions, and payroll details' },
      { id: 'performance', label: 'Performance', icon: FiTrendingUp, category: 'work', description: 'Goals, ratings, and review insights' },
      { id: 'settings', label: 'Settings', icon: FiSettings, category: 'work', description: 'Update profile preferences and account settings' },
    ],
  },
  [ROLES.MANAGER]: {
    portalLabel: 'Manager Control Center',
    heading: 'Team Operations Dashboard',
    subtitle: 'Monitor team performance, approve requests, and remove blockers.',
    widgets: [
      { key: 'team-attendance', title: 'Team Attendance Today', value: '0', note: 'Live team attendance snapshot from backend' },
      { key: 'leave-requests', title: 'Pending Leave Decisions', value: '0', note: 'Leave requests awaiting manager action' },
      { key: 'team-performance', title: 'Average Work Hours', value: 'N/A', note: 'Monthly effort trend generated from attendance summary' },
      { key: 'team-members', title: 'Direct Reports', value: '0', note: 'Active team members assigned to your reporting line' },
    ],
    pages: [
      { id: 'dashboard', label: 'Dashboard', icon: FiHome, category: 'main', description: 'Team KPIs and actionable updates' },
      { id: 'attendance', label: 'Attendance', icon: FiCalendar, category: 'operations', description: 'Daily attendance and punctuality tracking' },
      { id: 'announcements', label: 'Announcements', icon: FiBell, category: 'operations', description: 'Company updates and important notices' },
      { id: 'analytics', label: 'Analytics', icon: FiTrendingUp, category: 'operations', description: 'Team analytics and productivity trends' },
      { id: 'employee-profile', label: 'Employee Profile', icon: FiUser, category: 'operations', description: 'Profile and role details' },
      { id: 'team', label: 'Team', icon: FiUsers, category: 'operations', description: 'Direct reports and team member details' },
      { id: 'leaves', label: 'Leaves', icon: FiCalendar, category: 'operations', description: 'Approve and track leave requests' },
      { id: 'payroll', label: 'Payroll', icon: FiDollarSign, category: 'operations', description: 'Payroll summaries and payouts' },
      { id: 'performance', label: 'Performance', icon: FiTrendingUp, category: 'operations', description: 'Performance reviews and goals' },
      { id: 'reports', label: 'Reports', icon: FiBookOpen, category: 'operations', description: 'Attendance and performance reports' },
      { id: 'settings', label: 'Settings', icon: FiSettings, category: 'operations', description: 'Manager preferences and account settings' },
      { id: 'team-collaboration', label: 'Team Collaboration', icon: FiUsers, category: 'operations', description: 'Collaborate, communicate, and coordinate with teams' },
    ],
  },
  [ROLES.HR_ADMIN]: {
    portalLabel: 'HR Operations Center',
    heading: 'Workforce Operations Dashboard',
    subtitle: 'Run employee lifecycle operations across attendance, leave, and payroll.',
    widgets: [
      { key: 'total-employees', title: 'Active Employees', value: '0', note: 'Current workforce headcount from employee records' },
      { key: 'new-joiners', title: 'New Joiners (Month)', value: '0', note: 'Employees onboarded in the current month' },
      { key: 'pending-leaves', title: 'Leaves Awaiting Approval', value: '0', note: 'Pending leave requests requiring HR attention' },
      { key: 'payroll-processing', title: 'Payroll Runs', value: '0', note: 'Payroll cycle status across ongoing runs' },
    ],
    pages: [
      { id: 'dashboard', label: 'HR Overview', icon: FiHome, category: 'main', description: 'Organization-wide HR health summary' },
      { id: 'announcements', label: 'Announcements', icon: FiBell, category: 'operations', description: 'Create and send company announcements' },
      { id: 'leaves-attendance', label: 'Leaves & Attendance', icon: FiCalendar, category: 'operations', description: 'Manage leave flow and attendance records' },
      { id: 'manpower-planning', label: 'Manpower Planning', icon: FiBriefcase, category: 'operations', description: 'Workforce planning and staffing insights' },
      { id: 'hr-payroll', label: 'HR Payroll', icon: FiDollarSign, category: 'operations', description: 'Payroll operations and payouts' },
      { id: 'exit-clearance', label: 'Exit Clearance', icon: FiLogOut, category: 'operations', description: 'Handle separation and clearance process' },
      { id: 'meeting-room', label: 'Meeting Room', icon: FiMapPin, category: 'operations', description: 'Schedule meetings and room usage' },
      { id: 'workflows', label: 'Workflows', icon: FiRefreshCw, category: 'operations', description: 'Automate HR approval workflows' },
      { id: 'letter-templates', label: 'Letter Templates', icon: FiFileText, category: 'operations', description: 'Generate HR letters and documents' },
      { id: 'user-management', label: 'User Management', icon: FiUser, category: 'operations', description: 'Manage user accounts and access' },
      { id: 'masters', label: 'Masters', icon: FiGrid, category: 'operations', description: 'Departments, designations, and masters' },
      { id: 'admin-panel-config', label: 'Admin Panel Config', icon: FiSettings, category: 'operations', description: 'Configure HR admin panel behavior' },
    ],
  },
  [ROLES.SUPER_ADMIN]: {
    portalLabel: 'Enterprise Admin Center',
    heading: 'Governance Dashboard',
    subtitle: 'Oversee system governance, access control, and organizational structure.',
    widgets: [
      { key: 'company-overview', title: 'Organization Headcount', value: '0', note: 'Enterprise employee volume from live backend records' },
      { key: 'system-settings', title: 'Configured Roles', value: '0', note: 'Role and access model definitions in the platform' },
      { key: 'audit-logs', title: 'Active Sessions', value: '0', note: 'Authenticated sessions and access activity overview' },
      { key: 'department-stats', title: 'Departments', value: '0', note: 'Department structure and coverage across the company' },
    ],
    pages: [
      { id: 'dashboard', label: 'Overview', icon: FiShield, category: 'main', description: 'Enterprise risk, usage, and control summary' },
      { id: 'employees', label: 'Global Employees', icon: FiUsers, category: 'governance', description: 'Cross-organization employee governance controls' },
      { id: 'departments', label: 'Department Admin', icon: FiBriefcase, category: 'governance', description: 'Department setup and structural governance' },
      { id: 'announcements', label: 'Announcements', icon: FiBell, category: 'governance', description: 'Create and send announcements to employees' },
      { id: 'roles-permissions', label: 'Access Control', icon: FiLock, category: 'governance', description: 'Roles, permissions, and assignment management' },
      { id: 'system-settings', label: 'Platform Settings', icon: FiSettings, category: 'system', description: 'Core tenant and policy configuration' },
      { id: 'audit-logs', label: 'Compliance Logs', icon: FiFileText, category: 'system', description: 'Security and compliance activity trails' },
      { id: 'ui-components', label: 'UI Components', icon: FiGrid, category: 'system', description: 'Browse all dashboard widgets and cards' },
    ],
  },
};

export const SINGLE_DASHBOARD_ROLES = [];
