import {
  FiBell,
  FiBookOpen,
  FiBriefcase,
  FiCalendar,
  FiCircle,
  FiFileText,
  FiGrid,
  FiHome,
  FiLock,
  FiLogOut,
  FiMapPin,
  FiRefreshCw,
  FiSettings,
  FiShield,
  FiTrendingUp,
  FiUser,
  FiUsers,
  FiTool,
  FiLayers,
  FiClock,
  FiGitBranch,
  FiUpload,
  FiCheckSquare,
} from 'react-icons/fi';
import RupeeIcon from '../icons/RupeeIcon';
import { ROLES } from '../../utils/roles';

/**
 * Page / widget entries may include optional `visibility` (designation + department).
 * See `client/src/utils/dashboardVisibility.js` for behaviour. HR admin & super admin portals
 * are not filtered by org context so operational modules stay available org-wide.
 */

const PAGE_ICON_COMPONENTS = {
  dashboard: FiHome,
  attendance: FiCalendar,
  announcements: FiBell,
  analytics: FiTrendingUp,
  'employee-profile': FiUser,
  team: FiUsers,
  employees: FiUsers,
  'leave-management': FiCalendar,
  leaves: FiCalendar,
  payroll: RupeeIcon,
  performance: FiTrendingUp,
  reports: FiBookOpen,
  settings: FiSettings,
  'team-collaboration': FiUsers,
  'dashboard-overview': FiHome,
  'leaves-attendance': FiCalendar,
  'manpower-planning': FiBriefcase,
  'hr-payroll': RupeeIcon,
  'exit-clearance': FiLogOut,
  'meeting-room': FiMapPin,
  workflows: FiRefreshCw,
  'letter-templates': FiFileText,
  'user-management': FiUser,
  masters: FiGrid,
  'admin-panel-config': FiSettings,
  departments: FiBriefcase,
  'roles-permissions': FiLock,
  'system-settings': FiSettings,
  'audit-logs': FiFileText,
  'ui-components': FiGrid,
  'role-transfer': FiShield,
  recruitment: FiBriefcase,
  'tool-provisioning': FiTool,
  'projects-admin': FiLayers,
  'shift-management': FiClock,
  'org-structure': FiGitBranch,
  'employee-bulk-ops': FiUpload,
  'performance-management': FiTrendingUp,
  'attendance-approvals': FiCheckSquare,
};

export const attachMonoIconsToPages = (pages = []) => {
  return pages.map((page) => ({
    ...page,
    icon: typeof page.icon === 'function' ? page.icon : PAGE_ICON_COMPONENTS[page.id] || FiCircle,
  }));
};

export const ROLE_DASHBOARD_CONFIG = {
  [ROLES.EMPLOYEE]: {
    portalLabel: 'Employee Self-Service',
    heading: 'My Work Dashboard',
    subtitle: 'Manage attendance, leave, payroll, and documents in one place.',
    widgets: [
      { key: 'attendance', title: 'Attendance This Month', value: '0', note: 'Live attendance summary from your daily records' },
      { key: 'leaves', title: 'My Leave Requests', value: '0', note: 'Submitted and approved leave requests from backend' },
      { key: 'holidays', title: 'Upcoming Holidays', value: '0', note: 'Holiday calendar synced from company leave policy' },
      { key: 'payslip', title: 'Payslips Available', value: '0', note: 'Payroll statements available for secure download' },
    ],
    pages: [
      { id: 'dashboard', label: 'Dashboard', icon: FiHome, category: 'overview', order: 0, description: 'Personal HR summary and quick actions' },
      { id: 'attendance', label: 'Attendance', icon: FiCalendar, category: 'workplace', order: 10, description: 'Daily punch history and attendance status' },
      { id: 'leaves', label: 'Leaves', icon: FiCalendar, category: 'workplace', order: 20, description: 'Apply leave and track request progress' },
      { id: 'payroll', label: 'Payroll', icon: RupeeIcon, category: 'workplace', order: 30, description: 'Payslips, deductions, and payroll details' },
      { id: 'performance', label: 'Performance', icon: FiTrendingUp, category: 'workplace', order: 40, description: 'Goals, ratings, and review insights' },
      { id: 'employee-profile', label: 'My Profile', icon: FiUser, category: 'workplace', order: 50, description: 'Personal information and employment details' },
      { id: 'announcements', label: 'Announcements', icon: FiBell, category: 'communications', order: 10, description: 'Company updates and important notices' },
      { id: 'resignation', label: 'Resignation', icon: FiLogOut, category: 'separation', order: 10, description: 'Initiate and manage resignation processes' },
      { id: 'settings', label: 'Settings', icon: FiSettings, category: 'account', order: 10, description: 'Update profile preferences and account settings' },
    ],
  },
  [ROLES.MANAGER]: {
    portalLabel: 'Team Operations Dashboard',
    heading: 'Team Operations Dashboard',
    subtitle: 'Monitor team performance, approve requests, and remove blockers.',
    widgets: [
      { key: 'team-attendance', title: 'Team Attendance Today', value: '0', note: 'Live team attendance snapshot from backend' },
      { key: 'leave-requests', title: 'Pending Leave Decisions', value: '0', note: 'Leave requests awaiting manager action' },
      { key: 'team-performance', title: 'Average Work Hours', value: 'N/A', note: 'Monthly effort trend generated from attendance summary' },
      { key: 'team-members', title: 'Direct Reports', value: '0', note: 'Active team members assigned to your reporting line' },
    ],
    pages: [
      { id: 'dashboard', label: 'Dashboard', icon: FiHome, category: 'overview', order: 0, description: 'Team KPIs and actionable updates' },
      { id: 'team', label: 'My Team', icon: FiUsers, category: 'team', order: 10, description: 'Direct reports and team member details' },
      { id: 'team-collaboration', label: 'Collaboration', icon: FiUsers, category: 'team', order: 20, description: 'Collaborate, communicate, and coordinate with teams' },
      { id: 'analytics', label: 'Analytics', icon: FiTrendingUp, category: 'team', order: 30, description: 'Team analytics and productivity trends' },
      { id: 'reports', label: 'Reports', icon: FiBookOpen, category: 'team', order: 40, description: 'Attendance and performance reports' },
      { id: 'attendance', label: 'Attendance', icon: FiCalendar, category: 'workplace', order: 10, description: 'Daily attendance and punctuality tracking' },
      { id: 'leaves', label: 'Leaves', icon: FiCalendar, category: 'workplace', order: 20, description: 'Approve and track leave requests' },
      { id: 'payroll', label: 'Payroll', icon: RupeeIcon, category: 'workplace', order: 30, description: 'Payroll summaries and payouts' },
      { id: 'performance', label: 'Performance', icon: FiTrendingUp, category: 'workplace', order: 40, description: 'Performance reviews and goals' },
      { id: 'employee-profile', label: 'My Profile', icon: FiUser, category: 'workplace', order: 50, description: 'Profile and role details' },
      { id: 'announcements', label: 'Announcements', icon: FiBell, category: 'communications', order: 10, description: 'Company updates and important notices' },
      { id: 'attendance-approvals', label: 'Attendance Approvals', icon: FiCheckSquare, category: 'approvals', order: 10, description: 'Approve attendance corrections for your team' },
      { id: 'tool-provisioning', label: 'Tool Provisioning', icon: FiTool, category: 'approvals', order: 20, description: 'Approve or reject tool access requests' },
      { id: 'resignation', label: 'Resignation', icon: FiLogOut, category: 'approvals', order: 30, description: 'Approve and manage team resignation requests' },
      { id: 'performance-management', label: 'Performance Reviews', icon: FiTrendingUp, category: 'talent', order: 10, description: 'Team performance reviews and goals' },
      { id: 'settings', label: 'Settings', icon: FiSettings, category: 'account', order: 10, description: 'Manager preferences and account settings' },
    ],
  },
  [ROLES.DEPT_ADMIN]: {
    portalLabel: 'Department Admin Portal',
    heading: 'Department Operations',
    subtitle: 'Manage your department attendance, structure, and approvals.',
    widgets: [
      { key: 'dept-attendance', title: 'Pending Attendance', value: '0', note: 'Records awaiting your approval' },
      { key: 'dept-tools', title: 'Tool Requests', value: '0', note: 'Provisioning tickets for your department' },
      { key: 'dept-headcount', title: 'Department Headcount', value: '0', note: 'Active employees in your department' },
      { key: 'dept-performance', title: 'Open Reviews', value: '0', note: 'Performance cycles in progress' },
    ],
    pages: [
      { id: 'dashboard', label: 'Dashboard', icon: FiHome, category: 'overview', order: 0, description: 'Department summary and quick actions' },
      { id: 'attendance', label: 'Attendance', icon: FiCalendar, category: 'workplace', order: 10, description: 'Your attendance records' },
      { id: 'leaves', label: 'Leaves', icon: FiCalendar, category: 'workplace', order: 20, description: 'Leave requests and balances' },
      { id: 'attendance-approvals', label: 'Attendance Approvals', icon: FiCheckSquare, category: 'approvals', order: 10, description: 'Approve team attendance corrections' },
      { id: 'tool-provisioning', label: 'Tool Provisioning', icon: FiTool, category: 'approvals', order: 20, description: 'Tool access requests for your department' },
      { id: 'org-structure', label: 'Org Structure', icon: FiGitBranch, category: 'organization', order: 10, description: 'Hierarchy and reporting lines' },
      { id: 'performance-management', label: 'Performance', icon: FiTrendingUp, category: 'talent', order: 10, description: 'Reviews and goals for your department' },
      { id: 'settings', label: 'Settings', icon: FiSettings, category: 'account', order: 10, description: 'Account preferences' },
    ],
  },
  [ROLES.HR_ADMIN]: {
    portalLabel: 'HR Operations Center',
    heading: 'Workforce Operations Dashboard',
    subtitle: 'Run employee lifecycle operations across attendance, leave, and payroll.',
    widgets: [
      { key: 'total-employees', title: 'Active Employees', value: '0', note: 'Current workforce headcount from employee records' },
      { key: 'new-joiners', title: 'New Joiners (Month)', value: '0', note: 'Employees onboarded in the current month' },
      { key: 'pending-leaves', title: 'Leaves Awaiting Approval', value: '0', note: 'Pending leave requests requiring HR attention' },
      { key: 'payroll-processing', title: 'Payroll Runs', value: '0', note: 'Payroll cycle status across ongoing runs' },
    ],
    pages: [
      { id: 'dashboard', label: 'HR Overview', icon: FiHome, category: 'overview', order: 0, description: 'Organization-wide HR health summary' },
      { id: 'announcements', label: 'Announcements', icon: FiBell, category: 'communications', order: 10, description: 'Create and send company announcements' },
      { id: 'user-management', label: 'User Management', icon: FiUser, category: 'workforce', order: 10, description: 'Manage user accounts and access' },
      { id: 'profile-approvals', label: 'Profile approvals', icon: FiUser, category: 'workforce', order: 15, description: 'Review employee profile updates and onboarding' },
      { id: 'manpower-planning', label: 'Manpower Planning', icon: FiBriefcase, category: 'workforce', order: 20, description: 'Workforce planning and staffing insights' },
      { id: 'recruitment', label: 'Recruitment', icon: FiBriefcase, category: 'workforce', order: 30, description: 'Jobs, candidates, and interviews' },
      { id: 'employee-bulk-ops', label: 'Bulk Import', icon: FiUpload, category: 'workforce', order: 40, description: 'Bulk employee import and transfers' },
      { id: 'leaves-attendance', label: 'Leaves & Attendance', icon: FiCalendar, category: 'time-attendance', order: 10, description: 'Manage leave flow and attendance records' },
      { id: 'shift-management', label: 'Shifts', icon: FiClock, category: 'time-attendance', order: 20, description: 'Shift templates and employee assignments' },
      { id: 'attendance-approvals', label: 'Attendance Approvals', icon: FiCheckSquare, category: 'time-attendance', order: 30, description: 'Approve attendance corrections' },
      { id: 'hr-payroll', label: 'Payroll', icon: RupeeIcon, category: 'compensation', order: 10, description: 'Payroll operations and payouts' },
      { id: 'performance-management', label: 'Performance Reviews', icon: FiTrendingUp, category: 'talent', order: 10, description: 'Performance reviews and goals' },
      { id: 'org-structure', label: 'Org Structure', icon: FiGitBranch, category: 'organization', order: 10, description: 'Designation hierarchy and org chart' },
      { id: 'masters', label: 'Masters', icon: FiGrid, category: 'organization', order: 20, description: 'Departments, designations, and masters' },
      { id: 'projects-admin', label: 'Projects', icon: FiLayers, category: 'organization', order: 30, description: 'Project registry and assignments' },
      { id: 'exit-clearance', label: 'Exit Clearance', icon: FiLogOut, category: 'separation', order: 10, description: 'Handle separation and clearance process' },
      { id: 'resignation', label: 'Resignation', icon: FiLogOut, category: 'separation', order: 20, description: 'Manage and approve all resignation requests' },
      { id: 'tool-provisioning', label: 'Tool Provisioning', icon: FiTool, category: 'services', order: 10, description: 'IT tool access tickets' },
      { id: 'meeting-room', label: 'Meeting Rooms', icon: FiMapPin, category: 'services', order: 20, description: 'Schedule meetings and room usage' },
      { id: 'workflows', label: 'Workflows', icon: FiRefreshCw, category: 'services', order: 30, description: 'Automate HR approval workflows' },
      { id: 'letter-templates', label: 'Letter Templates', icon: FiFileText, category: 'services', order: 40, description: 'Generate HR letters and documents' },
      { id: 'admin-panel-config', label: 'Panel Configuration', icon: FiSettings, category: 'administration', order: 10, description: 'Configure HR admin panel behavior' },
    ],
  },
  [ROLES.SUPER_ADMIN]: {
    portalLabel: 'Enterprise Admin Center',
    heading: 'Governance Dashboard',
    subtitle: 'Oversee system governance, access control, and organizational structure.',
    widgets: [
      { key: 'company-overview', title: 'Organization Headcount', value: '0', note: 'Enterprise employee volume from live backend records' },
      { key: 'system-settings', title: 'Configured Roles', value: '0', note: 'Role and access model definitions in the platform' },
      { key: 'audit-logs', title: 'Active Sessions', value: '0', note: 'Authenticated sessions and access activity overview' },
      { key: 'department-stats', title: 'Departments', value: '0', note: 'Department structure and coverage across the company' },
    ],
    pages: [
      { id: 'dashboard', label: 'Overview', icon: FiShield, category: 'overview', order: 0, description: 'Enterprise risk, usage, and control summary' },
      { id: 'employees', label: 'Global Employees', icon: FiUsers, category: 'governance', order: 10, description: 'Cross-organization employee governance controls' },
      { id: 'departments', label: 'Departments', icon: FiBriefcase, category: 'governance', order: 20, description: 'Department setup and structural governance' },
      { id: 'org-structure', label: 'Org Structure', icon: FiGitBranch, category: 'governance', order: 30, description: 'Organization hierarchy and chart' },
      { id: 'roles-permissions', label: 'Access Control', icon: FiLock, category: 'governance', order: 40, description: 'Roles, permissions, and assignment management' },
      { id: 'role-transfer', label: 'Role Transfer', icon: FiShield, category: 'governance', order: 50, description: 'Transfer super admin credentials to another person' },
      { id: 'announcements', label: 'Announcements', icon: FiBell, category: 'governance', order: 60, description: 'Create and send announcements to employees' },
      { id: 'projects-admin', label: 'Projects', icon: FiLayers, category: 'governance', order: 70, description: 'Enterprise project registry' },
      { id: 'employee-bulk-ops', label: 'Bulk Import', icon: FiUpload, category: 'governance', order: 80, description: 'Bulk employee import and transfers' },
      { id: 'resignation', label: 'Resignation', icon: FiLogOut, category: 'separation', order: 10, description: 'System-wide resignation monitoring and controls' },
      { id: 'system-settings', label: 'Platform Settings', icon: FiSettings, category: 'system', order: 10, description: 'Core tenant and policy configuration' },
      { id: 'audit-logs', label: 'Compliance Logs', icon: FiFileText, category: 'system', order: 20, description: 'Security and compliance activity trails' },
      { id: 'ui-components', label: 'UI Components', icon: FiGrid, category: 'system', order: 30, description: 'Browse all dashboard widgets and cards' },
    ],
  },
};

export const SINGLE_DASHBOARD_ROLES = [];
